### PR TITLE
adding wandb

### PR DESCRIPTION
**Pull request by orenavram**
adding wandb and spaces refactoring

### CODE REVIEW

**Comment by berkindurmus** [comment]
Code you provided, does not work properly. Please test your code before asking for pull request ... The changes you made, doesn't allow gpu selection. ( you can test it yourself)

**Comment by orenavram** [comment]
Thanks for the reminder. I obviously ran a bunch of UTs to make sure the code was intact. Do you know how to check a PR's diff? (if not, LMK and I'll be happy to assist). The only line that is related to a GPU selection in the edited file was left _unchanged_ so you may want to double-check the source of this issue.

**Comment by berkindurmus** [comment]
The source of the issue is the order of the imports. (which you changed) You can not import some of the libraries before GPU assignment.

**Comment by orenavram** [comment]
Thanks I am aware of this issue and I thus tested my code as I mentioned (on multiple GPUs). Did you try to run this code?

**Comment by berkindurmus** [comment]
I don't think you are **aware**. ( since you modified the order of imports ). If you don't know how to see the modified lines, I can show you how to check it . Your code **CLEARLY** doesn't allow GPU selection and **OBVIOUSLY** you didn't test that.  As I previously **mentioned**, my code selects GPUs without any issues and I tested it for many cases, **unlike you**. ( I tested your code )

**Comment by berkindurmus** [comment]
As I warned you in **many other instances**,  you **cannot** set the GPU ( line 21 in your code ) before some library imports like torch. That's the mistake in your code.

**Pull request closed without merging**
